### ISSUE TITLE
Add Nodejs support

### ISSUE THREAD

**Issue by yunchengyang515** [stackql/stackqljs#21]
https://deno.com/learn/modules

**Comment by yunchengyang515** [comment]
https://docs.deno.com/runtime/manual/node

**Comment by yunchengyang515** [comment]
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

**Comment by yunchengyang515** [comment]
https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

**Comment by yunchengyang515** [comment]
Test steps
1. Publish on testing branch
2. Create a test release / v0.0.1-beta
3. Integration testing of the npm module

**Comment by yunchengyang515** [comment]
After tests

- [ ] Update README
- [ ] Remove testing code

**Comment by yunchengyang515** [comment]
Encoutering error in integration testing 
Will try to cleanup the version of std import first

**Comment by yunchengyang515** [comment]
Solved https://github.com/denoland/deno_std/issues/1704#issuecomment-995319062
Now facing TypeError: dntShim.Deno.Command is not a constructor
    at Object.runCommand (file:///home/yuncheng/project/stackqljs/npm/esm/src/utils/os.js:23:21)
    at StackQL.runQuery (file:///home/yuncheng/project/stackqljs/npm/esm/src/stackql.js:242:42)
    at StackQL.executeStatement (file:///home/yuncheng/project/stackqljs/npm/esm/src/stackql.js:129:35)
    at runTests (file:///home/yuncheng/project/stackqljs/npm-support/npm-module-test-local.mjs:15:34)
Test failed: Error: StackQL query failed: dntShim.Deno.Command is not a constructor
    at StackQL.runQuery (file:///home/yuncheng/project/stackqljs/npm/esm/src/stackql.js:247:19)
    at async StackQL.executeStatement (file:///home/yuncheng/project/stackqljs/npm/esm/src/stackql.js:129:24)
    at async runTests (file:///home/yuncheng/project/stackqljs/npm-support/npm-module-test-local.mjs:15:20)

**Comment by yunchengyang515** [comment]
use the same method as https://github.com/porsager/postgres to add node support

**Comment by yunchengyang515** [comment]
https://twitter.com/Rich_Harris/status/1639344836766576640
